### ISSUE TITLE
Unsupported operand types error after update

### ISSUE THREAD

**Issue by Asti128** [ConnectThink/WP-SCSS#102]
I used this plugin just fine until i updated to the latest version (1.2.4). Once i change a scss file now , i get this error:

Fatal error: Uncaught Error: Unsupported operand types in /www/htdocs/w00eb28e/test/lva/wp-content/plugins/wp-scss/scssphp/src/Node/Number.php:327 Stack trace: #0 /www/htdocs/w00eb28e/test/lva/wp-content/plugins/wp-scss/scssphp/src/Node/Number.php(278): Leafo\ScssPhp\Node\Number->normalizeUnits(0, Array, 'in') #1 /www/htdocs/w00eb28e/test/lva/wp-content/plugins/wp-scss/scssphp/src/Compiler.php(2710): Leafo\ScssPhp\Node\Number->output(Object(Leafo\ScssPhp\Compiler)) #2 /www/htdocs/w00eb28e/test/lva/wp-content/plugins/wp-scss/scssphp/src/Compiler.php(1662): Leafo\ScssPhp\Compiler->compileValue(Object(Leafo\ScssPhp\Node\Number)) #3 /www/htdocs/w00eb28e/test/lva/wp-content/plugins/wp-scss/scssphp/src/Compiler.php(1328): Leafo\ScssPhp\Compiler->compileChild(Array, Object(Leafo\ScssPhp\Formatter\OutputBlock)) #4 /www/htdocs/w00eb28e/test/lva/wp-content/plugins/wp-scss/scssphp/src/Compiler.php(1081): Leafo\ScssPhp\Compiler->compileChildrenNoReturn(Array, Object(Leafo\ScssPhp\Formatter\OutputBlock)) #5 /www/htdocs/w00eb28e/test/l in /www/htdocs/w00eb28e/test/lva/wp-content/plugins/wp-scss/scssphp/src/Node/Number.php on line 327

When i go back to the old version everything works fine again. What could be the problem here?

Thanks in advance
Asti

**Comment by garrettw** [comment]
If you can, please isolate the SCSS that is causing this.

**Comment by Asti128** [comment]
thanks for the hint, i didnt think it could be about 1 file, so i found it now :)

its this line:
$base-font: 'museo-sans', serif;

i cant name a variable base-font. as soon as i name it base-font2 everything works. 
I dont know why that is, but thanks a lot!

**Comment by Asti128** [comment]
thanks for the hint how to find out whats causing the problem.

This is causing it:

/* Fluid Gallery Columns
   works well if you remove the default gallery styling
   by adding the following to your functions.php
   add_filter( 'use_default_gallery_style', '__return_false' );
*/

@for $i from 2 through 9 {
	@include gallery_column( $i );
}
 Thank you!

**Comment by garrettw** [comment]
Thanks for posting that. The error is in your code, as I suspected.

1. Your mixin should be declared before it is used. Move the `@for` block *below* the `@mixin` block.
2. Your loop goes from 2 to 9, but in your 550px media query block, if `$num` is 2, you end up with a division by zero. To prove this, try changing your loop to be `3 through 9` and it should compile.

**Comment by Asti128** [comment]
awsome, works perfectly again now :)
