### ISSUE TITLE
Updating custom.css or custom.scss crashes site

### ISSUE THREAD

**Issue by vermontcc** [ConnectThink/WP-SCSS#103]
As the title of my issue says, Updating custom.css or custom.scss now crashes my site.  

I am now unable to make any changes to the sylesheets without creating fatal errors and rendering the site unresponsive.  The only way to get it back up and running is to use site backup to restore custom.css and/or costom.scss with their original timestamp; uploading an unmodified backup of those files (but with a newer timestamp) doesn't work either.  I did recently update the site to PHP 7.0 if that information is helpful.  

Finally, if I disable the WP-SCSS plugin, the site doesn't crash but the navigation menu is duplicated (see attached screenshot)

Site is https://vtfuturesproject.org

![screenshot-scss-disable](https://user-images.githubusercontent.com/8671558/40444998-e0355d38-5e98-11e8-8fdd-37f0f26d2604.png)

**Comment by shadoath** [comment]
@vermontcc Did you solve this or move to another plugin?
