### ISSUE TITLE
WP-SCSS and subdomains

### ISSUE THREAD

**Issue by actionhosting** [ConnectThink/WP-SCSS#105]
When setup in a subdomain  (sub.domain.tld)
Scss Location /sass/
CSS Location /

Wp-Scss: One or more specified directories does not exist. Please create the directories 

If exact setting are set in (domain.tld) all works

Scss Location /sass/
CSS Location /

**Comment by shadoath** [comment]
@actionhosting Can you provide some plugin output as to the folders that differentiate on a subdomain. 
This also may have been fixed with the new enqueueing patterns we are using.
