### ISSUE TITLE
Using theme test

### ISSUE THREAD

**Issue by martifenosa** [ConnectThink/WP-SCSS#107]
Is there a way to compile a non active theme? We are using Theme Test Drive plugin to adjust another theme but we can't compile unless we download it and run it on local.

**Comment by garrettw** [comment]
Not currently. They would have to add that functionality, and it's not a bad idea.

**Comment by shadoath** [comment]
There is now the option to set the base folder for your SCSS/CSS files to the plugin itself or the uploads folder. I'm thinking about how we can set this to a custom path in the future.
