### ISSUE TITLE
can i use parent and child themes and how?

### ISSUE THREAD

**Issue by katipierson** [ConnectThink/WP-SCSS#109]
Hello,

it is possible to use a child theme with WP-SCSS und a parent theme with wp-scss also?
How can i do this?
Do I need a filter or action in the functions. php?

Thanks!

**Comment by hellerbenjamin** [comment]
Yes, you can use it in a child theme. That would be the recommended way unless you are using a purely custom theme. I am not sure why you would want to use it in the parent theme although it would technically be possible. You do not need to do anything special for either, just configure the settings properly. Not filters or actions required, but do make sure you output CSS file is enqueued.

**Comment by katipierson** [comment]
Meanwhile, everything works wonderfully. I just needed the environment in the template. I want to use a theme for many domains. But I would like to do some things differently, depending on the environment.
