### ISSUE TITLE
Including plain CSS using @import?

### ISSUE THREAD

**Issue by willdelphia** [ConnectThink/WP-SCSS#110]
https://stackoverflow.com/questions/7111610/import-regular-css-file-in-scss-file

This thread talks about a means by which you can use a sass compiler to include raw, plain CSS into your compiled css file using @import.

In an attempt to automate the combination of all my CSS files in one. I was doing something like this:

@import 'bootstrap.min'
@import '_main.scss';
@import '_secondary.scss';
However when compiled this doesn’t work.

The resulting CSS file starts with @import 'bootstrap.min' rather than the contents of bootstrap.min.css.

Trying another option I changed the filename of bootstrap.min.css to _bootstap.min.scss and @imported that. This freezes the WP site entirely.

Any thoughts on if I can achieve an automated merge of all my scss and css files using WP-SCSS?

**Comment by willdelphia** [comment]
Thanks for the suggestion but I am getting the same behavior. When I load the site the browser's loading animation (in the tab) plays for about 30 seconds and when it stops it displays a blank page. Inspecting the source shows the document has some tags in the <head> section but nothing in <body>.

**Comment by garrettw** [comment]
What tags are in the `<head>`? What HTTP response code are you getting?
