### ISSUE TITLE
URL helpers (image-url) not working 

### ISSUE THREAD

**Issue by webunraveling** [ConnectThink/WP-SCSS#112]
I just discovered scssphp today and also your plugin. So I'm not sure which one would be the limitation. I'm in the process of testing out your plugin and noticed that, the [URL helper](http://compass-style.org/reference/compass/helpers/urls/), `image-url()` is not compiling.

The only URL helper I'm using is image-url because it does cache busting. I have not tested the other URL helpers.

**Comment by garrettw** [comment]
Compass is not part of either package.

I would recommend moving away from Compass anyway as that's the direction the Sass world is going, probably partly for increased portability.

**Comment by webunraveling** [comment]
Well dang... I just realized that was a function of Compass!

I better get to regexing my scss. ;-) Thanks for the quick reply.

**Comment by garrettw** [comment]
Although it doesn't have a replacement for that exact thing, you might like [Bourbon](https://www.bourbon.io/docs/latest/). The latest version is very trimmed down and minimalistic, but maybe you'd find something useful there.
