### ISSUE TITLE
Merging Selectors with the same name

### ISSUE THREAD

**Issue by Twilkey** [ConnectThink/WP-SCSS#113]
I can not find anything that tells me if this is possible, so I thought I would make a post.

Say I have 2 SCSS files.

**File 1:**
```
.some-selector {
  background-color: #fff;
}
```

**File 2:**
```
.some-selector {
  color: #000;
}
```

When I compile both these files into one CSS file is it possible to merge selectors with the same name so that inside the CSS file we would have this?
```
.some-selector {
  background-color: #fff;
  color: #000;
}
```

**Comment by garrettw** [comment]
I think the reason this is not done automatically is that it could break things if your CSS relies on a certain cascade where each rule needs to be evaluated sequentially in order to work as expected.
