### ISSUE TITLE
[Feature Request] More control over file locations

### ISSUE THREAD

**Issue by willcitizen** [ConnectThink/WP-SCSS#115]
Hi there.

I'm busy working with Oxygen builder and there are some good use cases for using wp-scss with Oxygen.

The issue though is that oxygen completely 'virtualises' the wordpress theme and doesn't set the theme directory.

I have worked around this creating a 'fake theme' folder and then modifying your code in two places to use get_theme_root()

wp-scss.php

// Plugin Paths
if (!defined('WPSCSS_THEME_DIR'))
    define('WPSCSS_THEME_DIR', get_theme_root());

and get_theme_root_uri()

class-wp-scss.php
 public function enqueue_files($css_folder) {

      foreach( new DirectoryIterator($this->css_dir) as $stylesheet ) {
        if ( pathinfo($stylesheet->getFilename(), PATHINFO_EXTENSION) == 'css' ) {
          $name = $stylesheet->getBasename('.css') . '-style';
          $uri = get_theme_root_uri().$css_folder.$stylesheet->getFilename();
          $ver = $stylesheet->getMTime();

It would be fantastic if you could implement a permanent (and hopefully more elegant solution) to provide some additional options for where the source and destination files are stored and queued from.

**Comment by dnnsjsk** [comment]
Hey,

This plugin makes it possible to use wp-scss with Oxygen :-)

https://github.com/srikat/oxygen-sass

**Comment by shadoath** [comment]
@willcitizen More options have been added.
