### ISSUE TITLE
Not working on Wordpress 5.0.2

### ISSUE THREAD

**Issue by fippy** [ConnectThink/WP-SCSS#119]
Since upgrading to 5.0.2, I haven't been able to get this plugin to work. For me at least, after making changes to scss file,  it does not want to write the css file.

I have tried various changes to permission and ownership and nothing seems to get it to work... I would appreciate some help?

**Comment by fippy** [comment]
turning off Enqueue Stylesheets seems to solved it??? - perhaps it was a clash with something else

**Comment by supernuca** [comment]
i n my case turning off enqueue stylesheets dont work. would be nice to get a fix soon ;)

**Comment by garrettw** [comment]
Yes, that's something every theme needs to have.

**Comment by fippy** [comment]
actually for me it seems to be a combination of creating a cache folder in the wp-scss plugin folder with webserver (www) permisions to write and also turning off  Enqueue Stylesheets

**Comment by shadoath** [comment]
@fippy Do you have any logs for this error? Unless you can help recreate this issue I'm going to close it.
The cache folder is now being created by default.
