### ISSUE TITLE
New scssphp

### ISSUE THREAD

**Issue by DoldersumSP** [ConnectThink/WP-SCSS#123]
Will you be updating to new scssphp? Fixes the following problem. https://github.com/leafo/scssphp/issues/614#issuecomment-450867551
I did a manual update to confirm.

**Comment by s7media** [comment]
Thank you, just done the same on the back of your comment. It looks like this plugin hasn't been updated in a while, might be worth getting a fork going.

**Comment by kilinkis** [comment]
Having the same issue. Also confirmed by manually updating the library.

**Comment by iannacone** [comment]
+1

**Comment by shadoath** [comment]
We are working to update from Leafo to SCSSPHP version 1.03 now.

**Comment by shadoath** [comment]
We have upgraded and will continue to do so. If there is a specific version of the new scssphp that is needed let me know.
