### ISSUE TITLE
How to overwrite Variables in Child-Theme

### ISSUE THREAD

**Issue by sbloss** [ConnectThink/WP-SCSS#124]
Hello,

for a multisite network i need my theme mutiple times but with different colors. So i tried to overwrite the colors variables in my child theme, but with no succes.

In my functions.php in include the output css file:
`add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {
wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
}`

How to setup a child theme using WP-SCSS (with Underscore theme https://underscores.me/ )?

Many thanks in advance!

**Comment by richrd** [comment]
@sbloss  did you find a solution to this? It would be nice to know how you did it.

**Comment by sbloss** [comment]
Hello @richrd ,

in my case i use a multisite network. every sub site has his own child theme. with this configuration it is easy to compile with "WP-SCSS" for every sub site a own style.css. the structure of the compiling file looks like:

@import "global_variables" (from parent theme)
@import "custom_variables" (individually for every child theme)
@import "global_theme_styles" (from parent theme)
@import "custom_theme_styles (individually for every child theme)

----------------

**alternative:** if you don't use a multisite network i found a alternative plugin "Lenix scss compiler" (https://de.wordpress.org/plugins/lenix-scss-compiler/). with this plugin you can compile mutiple files.

**plugin description:**

```
How It Works?

Choose a source folder for SCSS and a target folder for CSS.
Write the SCSS code in the file on the source folder, and it automatically creates a CSS file in the target folder.

What’s included?

- Option for multiple source and destination folders.
- Allows you to set a folder in the entire wp-content space.
- Performance – only when one of the source files change – it re-compiling itself.
- After development you can turn off / delete the plugin without fear, and all the files are stay where they were.
- Allows you to develop a theme and plugin at the same time.

```
i hope it helps you!

**Comment by richrd** [comment]
Thanks for taking the time to help! I'll probably be using this kind of approach in my next theme.
