### ISSUE TITLE
Option for outside the theme folder

### ISSUE THREAD

**Issue by pixeldesignstudio** [ConnectThink/WP-SCSS#127]
Hi,

on a new project, I don't use any bought themes. But on older project, there are installed themes and by updating them, it deletes the scss/css folder.

Therefore, it would be great to set the a folder outside the theme folder if possible.

Thx!

**Comment by shadoath** [comment]
@pixeldesignstudio, Yes. This has been a pain point for me as well. 

Similar idea mentioned this in #136.
