### ISSUE TITLE
Error with Bootstrap 4.3.1

### ISSUE THREAD

**Issue by severin10** [ConnectThink/WP-SCSS#129]
When importing the SASS version of bootstrap 4.3.1, I get the error:

> Sass Compiling Error
> "parse error: failed at `&} {` C:\xampp\htdocs\mediengruppe/wp-content/themes/theme_blank_bs/styles/sass/../bs4-sass/mixins/_badge.scss on line 5"

I'm just importing bootstrap.scss here, nothing else:

> @import "../bs4-sass/bootstrap.scss";

_badge.scss is part of the bootstrap package, I changed nothing here.
When I use another SASS compiler, I don't get errors. Could you please look into that?

**Comment by s7media** [comment]
Hi @severin10,

We're having a similar problem over at this thread:
https://github.com/ConnectThink/WP-SCSS/issues/123

In the end I've just been replacing scssphp/src folder with an updated folder from somewhere like here:
https://github.com/kingyond/scssphp

Seems to be working fine for me. Hope that helps.

**Comment by captaincoo1** [comment]
I'm getting these issues with Bootstrap 4.5 too. Going back to Bootstrap 4.2.1 or manually updating scssphp fixed it for me.

**Comment by shadoath** [comment]
We have upgraded to 1.0.3 and will continue to update the ScssPhp version.

@captaincoo1 & @severin10 What version of scssphp did you update to? 
@severin10 does upgrading to WP-SCSS 1.2.1 fix this?
