### ISSUE TITLE
Error en WP-SCSS

### ISSUE THREAD

**Issue by ana-paris** [ConnectThink/WP-SCSS#133]
Hola, estoy creando este comentario debido a que mi plantilla comenzó a generar un error que no he podido solucionar, el proyecto está alojado en mi servidor local o localhost, este es el error que muestra:

Sass Compiling Error
C:\xampp\htdocs\prueba/wp-content/plugins/wp-scss/cache/ 
"File Permission Error, permission denied. Please make the cache directory writable."

C:\xampp\htdocs\prueba/wp-content/plugins/wp-scss/cache/ 
"File Permission Error, permission denied. Please make the cache directory writable."

C:\xampp\htdocs\prueba/wp-content/plugins/wp-scss/cache/ 
"File Permission Error, permission denied. Please make the cache directory writable."

**Comment by ana-paris** [comment]
Gracias por el apoyo que me puedan dar, mi plantilla es dotdigital

**Comment by andreyc0d3r** [comment]
this error appears when /cache doesn't exist, I didn't look at the source code yet, but temporary you can create the folder manually

**Comment by yura-x** [comment]
As far as we waiting merging [this pull request ](https://github.com/ConnectThink/WP-SCSS/pull/135)
 you can try to use following action inside your theme/functions.php:
```
add_action( 'activate_wp-scss/wp-scss.php', 'PREFIX_action_create_cache_folder_to_wp_scss_plugin' );
if( ! function_exists( 'PREFIX_action_create_cache_folder_to_wp_scss_plugin' ) ) :
	function PREFIX_action_create_cache_folder_to_wp_scss_plugin() {
		$fs = WP_Filesystem();
		if( ! $fs ) {
			return;
		}
		global $wp_filesystem;
		if( ! $wp_filesystem->is_dir( WP_PLUGIN_DIR . '/wp-scss/cache' ) ) {
			$wp_filesystem->mkdir( WP_PLUGIN_DIR . '/wp-scss/cache' );
		}
	}
endif;
```

**Comment by shadoath** [comment]
PR merged and plugin updated.
