### ISSUE TITLE
SCSS compiler is two years old and needs to be updated

### ISSUE THREAD

**Issue by flip111** [ConnectThink/WP-SCSS#138]
Including foreign sources in source tree is bad practice.

Use either 

1. composer https://packagist.org/packages/scssphp/scssphp (preferred)
2. use git submodule https://github.com/scssphp/scssphp

Please update the compiler, people are having problems with invalid syntax for old compiler.

**Comment by flip111** [comment]
@brrn @kjayres24 will you merge when i open a PR for a new compiler version?

I realize that wordpress might not have the facilities to pull in additional git submodules or use composer (i didn't look into this). Is it possible to use method 1 or 2 ??

**Comment by garrettw** [comment]
As WP is not composer-based, all plugin dependencies have to either be packaged with the plugin or come in a separate plugin. Installing deps later with Composer is not an option for the vast majority of users.

**Comment by flip111** [comment]
@garrettw the maintainer needs to run composer, then package everything in a zip file and then submit it to wordpress https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/#where-do-i-submit-my-plugin

That wordpress doesn't use composer doesn't mean that the developer can't use it before packaging.

**Comment by garrettw** [comment]
also true.

**Comment by Franz-Kafka** [comment]
Any news on this topic?

**Comment by flip111** [comment]
You have to replace stuff from here https://github.com/ConnectThink/WP-SCSS/tree/master/scssphp with stuff from here https://github.com/scssphp/scssphp i fyou want to do it manually.

**Comment by shadoath** [comment]
@flip111 we have updated to ScssPhp 1.0.3 and plan to continue updates.

**Comment by shadoath** [comment]
Next PR #191 is now ready to be merged. Making a large jump in the ScssPHP version.

**Comment by shadoath** [comment]
ScssPhp updated to 1.5.2
