### ISSUE TITLE
PHP 7.4 Issue

### ISSUE THREAD

**Issue by jeffreysfridge** [ConnectThink/WP-SCSS#141]
When using the plugin I'm getting this message:

Notice: Trying to access array offset on value of type null in /wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 3705

When I downgrade PHP the issue goes away.

**Comment by Doc-hojo** [comment]
Got the exact same issue with 7.4.5, all goes back to normal on 7.3.17

**Comment by haithamalkhatib** [comment]
Same here...

**Comment by Doc-hojo** [comment]
Got rid of it by hidding notice in php

**Comment by candypaint514** [comment]
Ok I suppressed the notice only for the line of code that was affected. 

In the file:
 /wp-content/plugins/wp-scss/scssphp/src/Compiler.php Line 3705

You must add "@" before the line to suppress the notice - this would be a temporary fix and everything to appears to function normally. 

Before
`@$key = $key[1];@$key = $key[1];`


After 
`$key = $key[1];@$key = $key[1];`

**Comment by garrettw** [comment]
In production you should not be displaying errors at all but rather logging them.

**Comment by adamgreenough** [comment]
@garrettw I'd go as far as to say this plugin shouldn't even need be enabled in prod, since it saves out a CSS file fine. 

But you would want errors in dev, which is where this plugin is used mostly. Thank you to @candypaint514 for the patch! :)

**Comment by shadoath** [comment]
Note: after the update to ScssPhp the issue appears on line 4495 of Compiler.php. It looks like a check was added in future versions of [ScssPhp](https://github.com/scssphp/scssphp/blob/master/src/Compiler.php#L5861). I'm not going to patch our version but continue to update until we match the latest version.

**Comment by shadoath** [comment]
The plugin has been updated and requires PHP 7.4
