### ISSUE TITLE
Undefined mixin media

### ISSUE THREAD

**Issue by Trenbania** [ConnectThink/WP-SCSS#143]
Not sure if this is a bug or my setup.

I've installed two different themes on two different test sites so that I can play around and learn SASS. I'm using WP-SCSS to compile and it appears to be setup correctly.

However, I'm getting fatal errors:

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /srv/.../wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 1328

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /srv/.../wp-includes/class-wp-recovery-mode.php on line 169

These disappear if I remove include-media.scss from the theme.

I have little knowledge of SASS and that probably shows! Do you include include-media.scss? Is there any reason why I would get these errors that you are aware of?

**Comment by Trenbania** [comment]
Same happens when I up the PHP memory limit to 1024MB.  include-media.scss is here https://github.com/eduardoboucas/include-media

This is the main theme I've installed https://github.com/billerickson/EA-Genesis-Child and it SHOULD work out of the box. Bill doesn't use WP-SCSS and he tells me it works every time for him.

**Comment by garrettw** [comment]
Oh, nice find. I'll have to make a note of that library.

If I were a maintainer of this repo, I would start by upgrading to the latest version of scssphp (as requested in #138) and see if that fixes it. I have a hunch that it might.

**Comment by shadoath** [comment]
We have upgraded to version 1.0.3 of scssphp and plan to keep upgrading. I'm going to close this issue unless it can be replicated on a newer version of WP-SCSS (currently at 2.1.1).
