### ISSUE TITLE
Wp-Scss: SCSS directory does not exist

### ISSUE THREAD

**Issue by zeroanarchy01** [ConnectThink/WP-SCSS#146]
version 1.2.5
WP version : 5.3.4

even after setting the directory /theme/scss/ & /theme/css/ with and without the trailing slash it continuously presents the same warning.

Wp-Scss: SCSS directory does not exist

I have modified the folder permissions however this has not assisted. Appreciate any help you can provide to address this issue.

**Comment by pixeldesignstudio** [comment]
Hi, 

you only need /scss/ and /css/.
It's already in the /theme/ folder.

**Comment by zeroanarchy01** [comment]
Thanks Pixel very grateful.

**Comment by garrettw** [comment]
Please close this issue if it is resolved.
