### ISSUE TITLE
"File Permission Error, permission denied. Please make the cache directory writable."

### ISSUE THREAD

**Issue by Bharadwinesh** [ConnectThink/WP-SCSS#148]
"File Permission Error, permission denied. Please make the cache directory writable." I am getting this issue on my WordPress website, Can anyone help me??

**Comment by gcwebsites** [comment]
You need to make sure that it is writable by ownership and permissions. Make sure the folder is 755 and that the correct ownership is on the folder that it isn't root or something else.

**Comment by shadoath** [comment]
This will be fixed when #144 is merged and the cache folder is created by default.
