### ISSUE TITLE
set PHP Variables

### ISSUE THREAD

**Issue by Jim-E** [ConnectThink/WP-SCSS#15]
Hi,

In the WP-SCSS plugin I dropped in the latest leafo "scss.inc.php" which now supports setVariables
I need to use php variables, something like this:

functions.php

``` php
$tcolor_scss = '#000000';
$scssc->setVariables(array(
  'tcolor' => $tcolor_scss,
));
```

test.scss input:

``` css
p {color: $tcolor; }
```

test.css output:

``` css
p {color: ; }
```

I can echo it to the screen but can't get the plugin to compile it.
functions.php

``` php
$tcolor_scss_var = '#000000';
$scssc->setVariables(array(
  'tcolor' => $tcolor_scss_var,
));

echo $scssc->compile('@import "test.scss"' );
```

Screen output: p{color:#000;}

Any help would be greatly appreciated.

Thanks

**Comment by mkessler** [comment]
Was this feature ever added? Interested in using the plugin, but may be easier just to use the leafo compiler without the plugin if this hasn't been added.
