### ISSUE TITLE
[Feature Request] Add define('WP_SCSS_ALWAYS_RECOMPILE', true); to settings page

### ISSUE THREAD

**Issue by bick** [ConnectThink/WP-SCSS#151]
I had this idea when I was installing the plugin for the millionth time on a site, I always have to google the define('WP_SCSS_ALWAYS_RECOMPILE', true); code because I don't have it written down anywhere. It'd be very convenient if on the settings page, it was written at the bottom or something. I have to use it with pretty much all dev sites. 

Thanks

**Comment by shadoath** [comment]
@bick When you reference the Settings page can you be more specific? Do you want it in the readme of this repo or on the WP plugin page?

**Comment by aerothopter** [comment]
I'll just jump in here for my 2 cents -- I think @bick meant the WP plugin settings page. We have a similar workflow for our dev sites, and it's a pain to remember to enable the WP_SCSS_ALWAYS_RECOMPILE flag, and to disable it when we go live. It would be easier to simply have a checkbox for "Always recompile SCSS" in the WP plugin settings page.

**Comment by bick** [comment]
Yeah, @shadoath I meant the plugin settings page. Having it be there as a text snippet that you can simply copy and paste would be perfect, but @aerothopter's suggestion would be even more convenient.

**Comment by shadoath** [comment]
@bick @aerothopter please take a look at #162

**Comment by aerothopter** [comment]
I agree. From a UX perspective, if the `WP_SCSS_ALWAYS_RECOMPILE` flag was defined, then the checkbox would be disabled (i.e. locked to enabled/disabled) with a tooltip letting the user know that the setting is locked using the `WP_SCSS_ALWAYS_RECOMPILE` flag. And if it were not defined, the user would be able to use the checkbox as normal.

**Comment by shadoath** [comment]
<img width="683" alt="Screen Shot 2021-02-12 at 17 20 35" src="https://user-images.githubusercontent.com/1946020/107835410-a3f09480-6d56-11eb-9466-6196914875ec.png">
I think this feature is ready.
