### ISSUE TITLE
Version 1.2.5 update broke multi scss directory support?

### ISSUE THREAD

**Issue by zoukkinen** [ConnectThink/WP-SCSS#154]
After updating the plugin the old directory for scss stopped working. 

Previously we had the child and main theme scss directories listed as comma separated, like: 

`/scss/,../maintheme-base/scss/`

But after the update the comma separated folders just gives the error message.

**Comment by zoukkinen** [comment]
My bad, this feature was on our own fork of the plugin.
This issue can be closed.

**Comment by shadoath** [comment]
@zoukkinen Please submit the feature.
