### ISSUE TITLE
Latest update (2.0.0) changes Compiling mode to 'Expanded' and throws fatal error

### ISSUE THREAD

**Issue by davey013** [ConnectThink/WP-SCSS#159]
After the latest update (2.0.0) the compiling mode is automatically changed to 'Expanded' in the plugin settings (which was 'Compiled' before).

This update also throws a fatal error:

`Uncaught Error: Class 'Leafo\ScssPhp\Formatter\Compressed' not found in *****/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php:243`

Probably related to: https://github.com/ConnectThink/WP-SCSS/issues/157

To fix the fatal error I have to change the compiling mode back to 'Compressed' (or maybe just save the settings once, did not test that).

**Comment by shadoath** [comment]
Issue is due to value in database reading 'Leafo' instead of 'ScssPhp'. Saving will correct this as it stores correct value to DB. 
Take a look at #158, which will correct returned value. Saving still required to fix DB value.
