### ISSUE TITLE
WP - SCSS Not Working

### ISSUE THREAD

**Issue by sathishpurumani** [ConnectThink/WP-SCSS#170]
Hi,

I have updated wp-scss plugin v2.1.1 to v2.1.2. my site css files not loading. how to rollback old version.

**Comment by lukasz-matysiewicz** [comment]
Same, 
console says:
GET https://library/css/style.css net::ERR_NAME_NOT_RESOLVED
it not looking for Base Location

@sathishpurumani your hosting have backups everyday? if so, try to find plugin on your ftp and replace it

**Comment by davey013** [comment]
v2.1.2 made it even worse. When saving the settings now (with 'Current theme' as the base path), the correct path to the compiled CSS is not updating (!!).

It's loading:
//css/master/master.css?ver=1611914355

Instead of:
https://my-website.com/wp-content/themes/mytheme/css/master/master.css?ver=1611914355

**Comment by getrefined** [comment]
Agree with davey013 - now all sites have auto updated to 2.1.2 I can't fix by just saving in WP-SCSS settings.

**Comment by dazecoop** [comment]
Fix outlined here resolves the problem entirely.
https://wordpress.org/support/topic/2-1-2-breaks-everything/#post-14062210

Very far from ideal.

**Comment by pixeldesignstudio** [comment]
Can you please test it, before uploading any new version?

**Comment by sathishpurumani** [comment]
> Same,
> console says:
> GET https://library/css/style.css net::ERR_NAME_NOT_RESOLVED
> it not looking for Base Location
> 
> @sathishpurumani your hosting have backups everyday? if so, try to find plugin on your ftp and replace it
> 
> Edit: Yep, I downgraded to 2.0.1 and works fine

**Comment by sathishpurumani** [comment]
@lukasz-matysiewicz Thanks.

I have restore my backup. now my site is working fine.

**Comment by shadoath** [comment]
@sathishpurumani Version 2.1.3 is out. My apologies for moving too fast. Had my head full of other things while working on this and skipped testing.

**Comment by dazecoop** [comment]
@shadoath Thanks for fixing so promptly. Have tested on a dummy site of mine - seems to work OK & resolves the issue. Your code fix is the same as what I posted above (linked form WP forums), so feeling fairly confident about this. Cheers.
