### ISSUE TITLE
Why is "/css" being added to the file path?

### ISSUE THREAD

**Issue by shanestreator** [ConnectThink/WP-SCSS#171]
<img width="1114" alt="Screen Shot 2021-02-28 at 10 58 38 AM" src="https://user-images.githubusercontent.com/35476261/109427633-e2be5580-79b8-11eb-8c92-47eaa213275c.png">

**Comment by shadoath** [comment]
There are two relevant lines in the plugin that would show this in the wp-scss.php file. 
Line 127

**Comment by shanestreator** [comment]
@shadoath Yep, not sure what happened but my child theme somehow ended up having `/css` in the name. Appreciate the response...great plugin, thank you!

**User error or strange bug...more likely the former.**
Maybe this will help someone in the future - be careful with child themes and `/css` `/scss` directories. Or just don't be me and know what you're doing. :)
