### ISSUE TITLE
" Trying to access array offset on value of type null"

### ISSUE THREAD

**Issue by gcwebsites** [ConnectThink/WP-SCSS#173]
I get an error when backing up using All in One Migration. Using 2.1.4 and 2.1.3 is doing the same.

Wordpress 5.6.2 running PHP 7.4. Running WP CLI command to backup the site using All in One Migration.

`[root@dev public_html]# wp ai1wm backup --exclude-spam-comments --exclude-email-replace --exclude-cache
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 2672
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 2672
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 6131
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 2672
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 6131
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 2672
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 6131
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 2672
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 6131
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 2672
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 6131
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 2672
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 6131
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 2672
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 6131
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 2672
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 6131
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 2672
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 6131
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/wp-scss.php on line 269
Notice: Trying to access array offset on value of type null in /home/xxxxxxxx/public_html/wp-content/plugins/wp-scss/wp-scss.php on line 272
Backup in progress...
Success: Backup complete.`

The backup works, just get an error.

**Comment by shadoath** [comment]
Looks like an issue with the ScssPhp version we are on. The newest version has a [null check](https://github.com/scssphp/scssphp/blob/bb4f7f159316986e7c1bb3856a77bb5f759c1123/src/Compiler.php#L3291) in the reduces method.
That was a fix that was introduced in version [1.0.4](https://github.com/scssphp/scssphp/releases/tag/v1.0.4), which is only one minor bump ahead of where we are at now.
I'll look at updating this in the next week or so. If you want to create a PR please go ahead.

**Comment by shadoath** [comment]
ScssPhp updated to 1.5.2
