### ISSUE TITLE
Error while trying to upgrade WP-SCSS 2.0.0 to 2.1.4

### ISSUE THREAD

**Issue by stevearbour** [ConnectThink/WP-SCSS#174]
After upgrading the pluggin from 1.2.6 to 2.1.3, the website look totally broken, and like someone mentioned in another thread, the website look is back to the 90's  

I did a screenshoot of the setting from the 1.2.6, and tried to set the same setting in 2.1.3,  but when I load the site on the public side, and look in console, I have some error about css not loading: Instead of loading the CSS file such as **https://domainname/-path to theme-/assets/css/styles.css?ver=1614859739** it does fail by simply trying to load **https://assets/css/styles.css?ver=1614859739** which obviously fail with an 404 error.

How can I proceed with the update please ?

**Comment by stevearbour** [comment]
I need to add that I am able to download the version 2.0.0, and to install that over the 1.2.6 and it does seem to work fine, but the minute I try to upgrade to 2.1.1 it break the whole site, and I have these errors in the console, like described above

Thank you for your help in advance. !

**Comment by stevearbour** [comment]
2.1.4 still break the site, there something between 2.0.0 to 2.1.1 with the webpath to the assets that is failing.

**Comment by stevearbour** [comment]
*bump*, Any help ?

**Comment by stevearbour** [comment]
Actually, 1.2.6 was working fine, I tried to upgrade to 2.1.3, it failed, tried 2.1.4 it failed too, tried 2.0.0, it worked.

The problem is the path to CSS/SCSS is not right, it try to link to a relative path and it fail, while it work fine in 2.0.0 or 1.2.6. 

PHP 7.4.x / WP last version.

**Comment by stevearbour** [comment]
I think many others users are having the same issue: 

https://wordpress.org/support/topic/updating-from-2-0-1-2-1-1-breaks-css-completely/

**Comment by shadoath** [comment]
Good to see you have done some digging on your side, many don't and expect help from open source projects. 
You can look at the [releases](https://github.com/ConnectThink/WP-SCSS/releases) for this plugin and see the changes that have gone into each. You can also download a release from there.
I did create some bad releases specifically 2.1.1 and 2.1.2 I had thought those issues resolved. 
Have you been able to go into the settings and save them? Can you post your DB values before and after?

**Comment by stevearbour** [comment]
I am able to go in setting and save them, but updating from 2.0.0 branch to 2.1.4 is not updating these setting as it should.

There should be a small button to offer to reset setting to default (and perhaps create them in db if you renamed them or something)

**Comment by stevearbour** [comment]
I have access to the Database, would you be able to help me pin point the tables / location of these setting so that I can output them ?

**Comment by shadoath** [comment]
Look in the `wp_options` table for the option_name = 'wpscss_options'

I like the idea of a button to reset the default settings.

**Comment by stevearbour** [comment]
Right now, in a working state, with 2.0.0, it is at this:

a:6:{s:8:"scss_dir";s:13:"/assets/scss/";s:7:"css_dir";s:12:"/assets/css/";s:17:"compiling_options";s:34:"ScssPhp\ScssPhp\Formatter\Expanded";s:17:"sourcemap_options";s:15:"SOURCE_MAP_NONE";s:6:"errors";s:4:"show";s:7:"enqueue";s:1:"1";}

I had 1.2.6 before like I mentioned.

Let me try to copy the 2.1.4 folder over and then save setting, and recheck again.

**Comment by stevearbour** [comment]
After saving setting with 2.1.4 is this, I hidden private data :

`a:7:{s:21:"base_compiling_folder";s:89:"/home/username/domains/domain.name/private_html/wp-content/themes/mytheme";s:8:"scss_dir";s:13:"/assets/scss/";s:7:"css_dir";s:12:"/assets/css/";s:17:"compiling_options";s:34:"ScssPhp\ScssPhp\Formatter\Expanded";s:17:"sourcemap_options";s:15:"SOURCE_MAP_NONE";s:6:"errors";s:4:"show";s:7:"enqueue";s:1:"1";}`

**Comment by stevearbour** [comment]
![image](https://user-images.githubusercontent.com/4413101/110071168-93c24880-7d49-11eb-9865-d1abd5cbfe26.png)

**Comment by stevearbour** [comment]
it is missing the http(s) scheme, the base domain name and path to the theme, to link these css, and that why it isn't working.

**Comment by stevearbour** [comment]
if I revert back by simply deleting 2.1.4 and recopy 2.0.0, it work again.

**Comment by stevearbour** [comment]
Please let me know if I can assist you further.

**Comment by shadoath** [comment]
It is definitely related to how `$base_compiling_folder` got introduced and is not being used. I think the way it is enqueued and the way the folder structure is set up I must have missed something when adding this.  Going to sleep on it and see what I can do in the following days.  Thank you for your diligence in looking into this and providing good data to test on.

**Comment by stevearbour** [comment]
Anytime, just reply to me and I'll be glad to run test for you. Thanks

**Comment by shadoath** [comment]
Looking at it I think the [enqueue  URL](https://github.com/ConnectThink/WP-SCSS/compare/2.0.0...2.1.4#diff-2ccc11b1d0241444bc0e36b7b314b8d15834eac41b73c9511a5a1e06998b9af3R219) got changed to a path.
Can you see if #175 will fix it?

**Comment by stevearbour** [comment]
I tried this branch, WP-SCSS-enqueue-url-not-path, and it didn't work.

**Comment by stevearbour** [comment]
I still experience the same issue in console, the address to css and asset seem to be missing the theme path, the scheme is there, the domain is there, but the path to the theme is not there, resulting in a inexistant url and 404 on the .css which break the look

**Comment by shadoath** [comment]
I had thought that would do it. Can you post what you're getting and what would be the expected output?

**Comment by stevearbour** [comment]
As described just above.

**Comment by stevearbour** [comment]
If you could add the active theme path properly to the .css links you generate in the header, that would fix it.

**Comment by stevearbour** [comment]
do you need any special output from me ?

**Comment by stevearbour** [comment]
*Bump* : Is there anything I can do to help ?

**Comment by shadoath** [comment]
@stevearbour When you tried #175 What was the result of the [var_dump($uri)](https://github.com/ConnectThink/WP-SCSS/pull/175/files#diff-2ccc11b1d0241444bc0e36b7b314b8d15834eac41b73c9511a5a1e06998b9af3R223)?

**Comment by shadoath** [comment]
Are you using a Child theme?

**Comment by stevearbour** [comment]
No output from the var_dump at all in the source from the homepage. But the CSS ain't loading, and once again, the path to theme is missing in the generated address.

**Comment by shadoath** [comment]
That you are not getting any output from the `var_dump` is an indication that something is not correct before that. However, that is where the styles are enqueued and where the full path would be generated.  I don't have the same issue you are running into thus debugging this is not straightforward as having an issue and working to debug until it is fixed. 
On line 216 of `class/class-wp-scss.php` add these lines before the foreach loop:
```
var_dump($base_folder_path);
var_dump($get_home_path());
var_dump($relative_path);
var_dump($enqueue_base_url);
```

I work on this plugin in my free time and without pay as a way to better my programming skills and offer something back to the community.  If you want help with this, do so by being respectful, not demanding. Or better yet go into the code yourself and add debugging outputs, narrow down what the issue is and then propose the code that will be a solution.

**Comment by stevearbour** [comment]
One of the problem I see is that $get_home_path() should be get_home_path(),

The first two give me absolute local path to the website, the last two give me NULL. 

I hope this help you

**Comment by shadoath** [comment]
Looks like someone was able to [spot an issue](https://github.com/ConnectThink/WP-SCSS/pull/179) and add a check with `realpath()` to the enqueue files. I'm going to look later tonight at both of these. Wanted to give you a heads up incase this might also be the solution here.

**Comment by stevearbour** [comment]
I'll be glad to test for you, just tag me to summon me.

**Comment by shadoath** [comment]
@stevearbour what are the results of [2.1.5](https://github.com/ConnectThink/WP-SCSS/releases/tag/2.1.5) for you?

**Comment by stevearbour** [comment]
Give me a hour to test it.

**Comment by stevearbour** [comment]
Sound like this fixed it. Thank you again for your help. At least now there is a upgrade path from 1.2.6 to 2.0.0 to 2.1.5.
