### ISSUE TITLE
getting fatal error in version 2.1.3

### ISSUE THREAD

**Issue by laraWebM** [ConnectThink/WP-SCSS#176]
error log: PHP Fatal error:  Class '' not found in ***/wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 243

any ideas how to fix? activating plugin crashes whole site.

demo site:
https://www.larawebmarketing.com/_projects/callblending/

WordPress version: 5.6.2
PHP Version: 5.6.40

let me know what else you need to debug.

thank you.

**Comment by Bsoubrevilla** [comment]
Hello, i have the same issue. After several test, i discovered it was due to "define('WP_SCSS_ALWAYS_RECOMPILE', true);" in my functions.php. I have a topic open about that actually and i am waiting/looking for an answer too, but removing that can fix it until we got a better fix.

**Comment by shadoath** [comment]
@laraWebM Any insight on this? Did removing WP_SCSS_ALWAYS_RECOMPILE fix it?
@Bsoubrevilla I have looked at where WP_SCSS_ALWAYS_RECOMPILE is used in the code and don't see how that would be related. Any luck in your search?
I'm planning an update the PhpScss library version which may help.

**Comment by shadoath** [comment]
ScssPhp updated to 1.5.2
