### ISSUE TITLE
Add Parent Theme as option to Base Location

### ISSUE THREAD

**Issue by anebi** [ConnectThink/WP-SCSS#177]
Hello,

We are successfully using WP-SCSS and we are really happy with it, but I have a small request that I think shouldn't be a problem to be added for you.

We would like to have Parent Theme as an option in Base Location dropdown.

Right now we have Parent/Child theme usage model, but we have multiple SCSS files in parent theme and we would like to set WP-SCSS to generate the css files for them, because we don't use include of all those scss files into a main file. The reason for this is that we try to minify CSS usage and use only needed css, so we need WP-SCSS to give us an option to select Parent Theme in Base Location dropdown instead of setting Current Theme (in our case child theme). Like this can set parent paths for scss and css dirs instead of in child theme.

Thank you in advance.

Best regards,
Ali Nebi

[wp-scss-patch.txt](https://github.com/ConnectThink/WP-SCSS/files/6111334/wp-scss-patch.txt)

<img width="1264" alt="Screenshot 2021-03-09 at 22 40 02" src="https://user-images.githubusercontent.com/225278/110535693-42d79900-8129-11eb-9df6-87fbc20e2cf6.png">

**Comment by shadoath** [comment]
Thank you for the notes. 
[Here](https://github.com/ConnectThink/WP-SCSS/pull/178) is what I'm thinking.
I think this may have an impact on the enqueueing of css files, thus only a draft. You can pull down the branch and test if you would like.

**Comment by anebi** [comment]
Thank you. I will pull down the branch and do some tests. We are already using it with the patched version but we don't use enqueue option from plugin as our theme is custom, we do enqueue different way directly from theme and guttenberg blocks.

But yeah, enqueue  stuff is a good note and should be checked. I will run some tests.

**Comment by shadoath** [comment]
@anebi,  I updated the pr and set it ready to review. Can you test out that branch and let me know you see all 4 options for the "Base Directory"?

**Comment by anebi** [comment]
Hi, It looks like working. I see that the changes were merged already to a new released version of the plugin. So all good. Thanks a lot. I believe that we can close the ticket.
