### ISSUE TITLE
When do new versions appear on wordpress.org/plugins?

### ISSUE THREAD

**Issue by mmcev106** [ConnectThink/WP-SCSS#183]
It looks like the 2.1.5 tag was made almost a month ago, but 2.1.3 is still the latest released version:
https://wordpress.org/plugins/wp-scss/

**Comment by mmcev106** [comment]
I believe [this PR](https://github.com/ConnectThink/WP-SCSS/pull/185) fixes an issue in 2.1.5, in case we want to wait to release until that PR is merged, or some other solution is in place.

**Comment by shadoath** [comment]
@mmcev106 Good catch, I stepped away from this project for a bit when my new job took my full focus. I must have tagged a new version here and not updated the WP svn thus not updating that version. 
Let's review #185 and I'll work to merge that in this week then update the SVN.

**Comment by mmcev106** [comment]
Thanks for the response, and congrats on the new job!  I guess I'll go ahead and close this.
