### ISSUE TITLE
Parse error when CSS :not() used

### ISSUE THREAD

**Issue by benhuson** [ConnectThink/WP-SCSS#184]
I presume this is down to the version of the compiler that is used, but a Sass Compiling Error is currently thrown whoever it encounters CSS `:not()` syntax in our SASS files.

**Comment by shadoath** [comment]
I would assume the same. I would like to bump the ScssPHP version soon. If you want to submit a PR with updates please do else I'll do it when there is time.

**Comment by shadoath** [comment]
@benhuson can you give an example of the content of the `:not()` that you are using. 
Please also test out #191 with the updated scssPHP version.

**Comment by darrennix** [comment]
I had the same issue when compiling Boostrap5 from source.

Updating to the latest version fo scssPHP resolved the issue.

**Comment by shadoath** [comment]
WP-SCSS now uses ScssPhp 1.5.2.
