### ISSUE TITLE
Undefined array key 1 in class-wp-scss.php on line 215

### ISSUE THREAD

**Issue by farhanjiwani** [ConnectThink/WP-SCSS#186]
There was an undefined key in my local WAMP setup.

The line is `$relative_path = explode(get_home_path(), $base_folder_path)[1];`

I found that the `$base_folder_path` that was being passed with Windows style directories`\` and `get_home_path()` was returning Linux style `/` ones.

I added this line at the top of the function to get it to work for my needs, but I'm sure you can find a more elegant way to fix this problem as it's been years since I've dabbled with PHP:

`$base_folder_path = str_replace("\\","/",$base_folder_path);`

**Comment by shadoath** [comment]
Hey @farhanjiwani I believe this was fixed in #179. What version of WP-SCSS are you using?

**Comment by shadoath** [comment]
Also, take a look at #185 I think this may be an even better solution.

**Comment by shadoath** [comment]
Fix now merged and part of version 2.1.6
