### ISSUE TITLE
How to make sure the css rule generated by wp-scss override other css files?

### ISSUE THREAD

**Issue by newjie** [ConnectThink/WP-SCSS#201]
To elaborate, my theme has a css rule
`h3{line-height: 0.8em}`

I want to override it by simply putting
h3{line-height:1.2} in the custom scss file used by wp-scss.

**Comment by gcwebsites** [comment]
You need to make it important:
`h3{line-height:1.2 !important;}`

That should work.

**Comment by newjie** [comment]
`!important` is not a very good practice in my case. Sometimes it messes up with other rule.
I was asking how to make sure the css file generated by wp-scss be loaded after all of the other css files.

**Comment by gcwebsites** [comment]
Well then you would need to disable the WP-SCSS enqueue and do it through your functions.php file with it being a higher priority.

**Comment by shadoath** [comment]
As @gcwebsites is getting at this is more about CSS priorities than the plugin... However, you can make a `_settings.scss` file that will load before all the others with your defaults. Notice the `_` this will skip the main compiler then you can include it into your other scss files by doing `@import 'settings';`

**Comment by shadoath** [comment]
I also believe scss files are compiled in alphabetic order which might be directly related to your use case.
