### ISSUE TITLE
Wordpress Directory: Plugin closure?

### ISSUE THREAD

**Issue by mhbapcc** [ConnectThink/WP-SCSS#203]
Hi,
Is there any info on why this plugin has been closed? Wondering if there’s cause for concern or whether it’s just a temporary issue. Hoping the closure isn’t permanent, WP-SCSS is extremely useful.

Thanks.

**Comment by razorfrog** [comment]
I'd also love to know what's going on. Thank you!

**Comment by guidofd** [comment]
+1

**Comment by jomourad** [comment]
+1

**Comment by agkovalev** [comment]
+1

**Comment by gcwebsites** [comment]
Based on the message I would assume it has been done by the Wordpress team pending some sort of review.

**Comment by yaniv691** [comment]
+1

**Comment by shadoath** [comment]
Hey Everyone, I’m looking into this more.

I didn’t get any notice from WordPress about this closure.
I have contacted the primary owner Connect Think, to see if they have more info and we will work to resolve this issue.

**Comment by shadoath** [comment]
Turns out the email that was associated with the WP account had not been updated in years and bounced when WordPress tried to email it.  This has been updated and we have informed WP today that the plugin is ready for review.  Hopefully, this will be resolved shorty.

**Comment by shadoath** [comment]
[PR](https://github.com/ConnectThink/WP-SCSS/pull/208) with fixes requested by WP

**Comment by shadoath** [comment]
This plugin was reviewed by WordPress and we are again live!
