### ISSUE TITLE
Latest version breaks my !global variables

### ISSUE THREAD

**Issue by scooterlord** [ConnectThink/WP-SCSS#206]
Hello, first of all I hope the issue with the closure is resolved soon!

Besides that, I am using custom functions to create responsive classes. The way I am doing it, is to set a global variable using `globalprefix:XX` and then change it from within a function like so `globalprefix: XXnew !global`. Currently this is not working and is breaking all my responsive classes. 

Edit: Carefully examined the plugin updates - looks like the compiler has been changed. I would suggest to add a dropdown to allow users to select which scssphp version suits them best to avoid such problems - if a previous version works best for a user then allow him to keep it. I don't have a similar problem with my local compiler or on sassmeister playground, so I have no idea how to investigate/fix this and would have to wait for an update.

Edit2: After 3 hours of debugging, I came to the following conclusion - what is broken is that for some reason global variables updated inside a mixin cannot be used inside `@content` used in the same mixin - otherwise global variables work as expected AND can be changed from inside mixins.

Below is a simplified example that fails - updating the `$globalprefix` inside a mixin **cannot** is not recognised inside `@content` although it used to be working properly a couple of versions back. As a reminder it works normally on sassmeister and on my local compiler (scout).
```
$globalprefix:null;

@mixin make-responsive($breakpoints:$breakpoints) {
  @each $prefix, $val in $breakpoints {
    @include responsive-class($prefix, $val, $breakpoints:$breakpoints) {
      $globalprefix: '-'+$prefix !global;
      @content;
    }
  }
}
```

As a solution, in newer versions you can in fact pass a variable to `@content` like `@content($var)` and then make use of this inside the mixin like below:

```
@include someMixin() using ($var) { 
  .yourclass {
    yourproperty:$var;
  }
}
```

More information for people ending up here: https://sass-lang.com/documentation/at-rules/mixin#passing-arguments-to-content-blocks

**Comment by shadoath** [comment]
Take a look at #233 to see if having ScssPHP v1.10 will fix your issue
