### ISSUE TITLE
Notice: Undefined index: compiling_options

### ISSUE THREAD

**Issue by alianschiavoncini** [ConnectThink/WP-SCSS#209]
Hello,
first of all, let me say, thank you for your code, it's very useful!!!

Today, I got a fatal error due to a non existing array key $option_values['compiling_options'] at line 144, file wp-scss.php.

I replaced your wpscss_plugin_db_cleanup function with this additional code that checks if the array has the compiling_options before made any replacing.

```
function wpscss_plugin_db_cleanup($option_values){
	if( array_key_exists('compiling_options', $option_values) ) {
		$compiling_options = str_replace("Leafo", "ScssPhp", $option_values['compiling_options']);
		$compiling_options = str_replace("ScssPhp\\ScssPhp\\Formatter\\", "", $compiling_options);
		$compiling_options = str_replace(["Compact", "Crunched"], "compressed", $compiling_options);
		$compiling_options = str_replace("Nested", "expanded", $compiling_options);
		$compiling_options = strtolower($compiling_options);
		$option_values['compiling_options'] = $compiling_options;
	}
  return $option_values;
}
```

Do you guess it could be implemented in your repository?

Moreover, why do you have the plugin pending review on WP repository?

Thank you,
Alian

**Comment by shadoath** [comment]
Glad to hear this plugin is very useful @alianschiavoncini.

 In version 2.3.0 we migrated the[ options for compiling](https://github.com/ConnectThink/WP-SCSS/pull/194/files#diff-59fa49bb5fe9384e9add561605d29ae06697bc970ad1321e97f63033ea87f17bL140-R139). Leaving only Compressed and Expanded. Which lead me to add this check. Thank you for the additional logic to only run if needed.
 
 As for the Pending state, that was removed yesterday! You can view this issue #203 to learn more.

**Comment by alianschiavoncini** [comment]
@shadoath thank you for reply!
