### ISSUE TITLE
[WEBSITE CRASHING BUG] Version 2.3.2 crashes my website when saving settings

### ISSUE THREAD

**Issue by KevinBTTR** [ConnectThink/WP-SCSS#210]
I just started a new website, and wanted to set the directories for css and scss. Whenever I hit save, a big critical error appears on screen: 
![image](https://user-images.githubusercontent.com/89904385/131637771-49c25f38-5982-495e-bf5f-7bc9c80ba0f1.png)

When I delete the plugin directory and reinstall, I can't activate the plugin because of this error. Downgrading to an older version of the plugin also gives the same error.

The only solution for me was to empty the database and start over.

This also happens in the TwentyTwentyOne Theme.

I also found out the checkboxes next to 'enqueue stylesheets' and 'always recompile' are turned into regular text fields: ![image](https://user-images.githubusercontent.com/89904385/131637801-96b34246-8b73-40b8-ae1a-2b8c68379094.png)

Please fix this ASAP as this literally can break websites

**Comment by webundso** [comment]
Same here with my own theme. Switched back to Version 2.3.0.
Search in DB table options for %scss% and erase these entries, reinstall wp-scss with version 2.3.0.

**Comment by shadoath** [comment]
My bad, a fix for this is out with v2.3.3, just pushed it up to WP plugins
