### ISSUE TITLE
Source Map Issue

### ISSUE THREAD

**Issue by gcwebsites** [ConnectThink/WP-SCSS#227]
PHP v 8.0
Wordpress 5.8.3
WP-SCSS v 2.4.0

Error is:
` Fatal error: Uncaught Error: ScssPhp\ScssPhp\SourceMap\SourceMapGenerator::normalizeFilename(): Argument #1 ($filename) must be of type string, null given, called in /home/gallb/public_html/wp-content/plugins/wp-scss/scssphp/src/SourceMap/SourceMapGenerator.php on line 165
in /home/gallb/public_html/wp-content/plugins/wp-scss/scssphp/src/SourceMap/SourceMapGenerator.php on line 303`

**Comment by shadoath** [comment]
@gcwebsites do you want to try the #233 which is an update to scssPHP v1.10?

**Comment by shadoath** [comment]
@gcwebsites can you try version 4.0.2?
