### ISSUE TITLE
File Permission Error, permission denied. Please make the cache directory writable.

### ISSUE THREAD

**Issue by bradical1379** [ConnectThink/WP-SCSS#229]
I'm running WP 5.9 on PHP 8.0 with the `cache` directory being set to `0755` permissions and I keep getting this error:

```
Sass Compiling Error
/nas/content/live/<sitename>/wp-content/plugins/wp-scss/cache/ 
"File Permission Error, permission denied. Please make the cache directory writable."
```
Is there anything that can be done as a work around to not need to write to the cache each time the code compiles?

**Comment by gcwebsites** [comment]
Is the ownership correct?

Providing the folder is there with the correct ownership and 0755 permissions (which is right) then you should be fine.

I've never had a problem and if I have its because I made a stuff up with the ownership.

**Comment by bradical1379** [comment]
> Is the ownership correct?
> 
> Providing the folder is there with the correct ownership and 0755 permissions (which is right) then you should be fine.
> 
> I've never had a problem and if I have its because I made a stuff up with the ownership.

I will have to double check on the ownership. I am hosting the site through WP Engine, which installs WP core differently, so there could be a catch in there with the way the files are created for each install.

**Comment by bradical1379** [comment]
> I thought you were using WP Engine based on the file path.
> 
> There is a fix permissions in the WP Engine portal. Run that, and then wait 5 mins, should be right after that. I've had to do that before for clients. All depends if you make the file via FTP or SSH. But if you do the reset permissions, it should standardize everything.

Thanks. I will try that, 

Strangely, the error message does not appear all of the time after compiling. I had wondered if something were also getting cached from WPE.

**Comment by gcwebsites** [comment]
> Strangely, the error message does not appear all of the time after compiling. I had wondered if something were also getting cached from WPE.

Wouldn't have thought so, I've never had that issue.

**Comment by bradical1379** [comment]
> > Strangely, the error message does not appear all of the time after compiling. I had wondered if something were also getting cached from WPE.
> 
> Wouldn't have thought so, I've never had that issue.

Even after resetting permissions for the site, I am still experiencing this issue. It doesn't happen on every page refresh, but most page reloads cause the error to pop-up.

**Comment by bradical1379** [comment]
Quick update on this. Spoke to WPE customer service. They have turned off the cache for the site and the error has stopped occuring.
