### ISSUE TITLE
Update scssphp to v1.10.0

### ISSUE THREAD

**Issue by pixelbart** [ConnectThink/WP-SCSS#230]
Most of the mentioned problems of the others, can be fixed with an update of [scssphp][1]. Also problems with Bootstrap 5 are solved this way.

You can have a look at it. It was really enough for me to update the scssphp folder in your plugin.

Currently I use **v1.10.0** and have no more problems.

[1]: https://scssphp.github.io/scssphp/

**Comment by shadoath** [comment]
Getting ready to release a v3.0 with this update #233

**Comment by shadoath** [comment]
Done!
And now we are even on v1.11 of SCSSPHP
