### ISSUE TITLE
":not()" is crashing Wordpress

### ISSUE THREAD

**Issue by blickwerker** [ConnectThink/WP-SCSS#231]
Empty selector list in the not() pseudo class is crashing the site.

Example CSS for reproduction:
`.class:not()`

**Expected behavior**
The CSS specification allows empty selector list for the not() pseudo class, so error free compilation is expected.

**Comment by shadoath** [comment]
Take a look at #233 to see if having ScssPHP v1.10 will fix your issue

**Comment by shadoath** [comment]
@blickwerker did you try the latest version of the plugin?

**Comment by shadoath** [comment]
@blickwerker did you try the latest version?

**Comment by blickwerker** [comment]
WPSCSS 4.0.2

This is working:
![image](https://user-images.githubusercontent.com/2408442/213068303-2e88c846-8de5-4094-95b4-37dfa2dc7aca.png)

and this leads to an critical wordpress error:
![image](https://user-images.githubusercontent.com/2408442/213068453-89ab268e-7b0d-4a49-86c0-77a34b6ba875.png)

**Comment by gcwebsites** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/:not

> The :not() pseudo-class requires a comma-separated list of one or more selectors as its argument.

You need to have a value for the ```not()``` function.

This isn't a plugin error, but more a coding error from what I can see.

**Comment by blickwerker** [comment]
shame on me, I was sure the specification allows an empty selector, but this indeed isn't the fact.
