### ISSUE TITLE
Can not change colors

### ISSUE THREAD

**Issue by ChrisSocentic** [ConnectThink/WP-SCSS#232]
When we want to change the colors via the customizer, it always breaks the web page. First there is a message "Error. Did you set up your WP SCSS plugin directories correctly?", then we create it. After that the page is damaged if we want to change the colors. Can anyone help me?

**Comment by shadoath** [comment]
Where do you have your base path set to? Try saving it to the `uploads` directory or the plugin. Then create your directories there.

**Comment by shadoath** [comment]
@ChrisSocentic Can you provide better steps to what went wrong?
