### ISSUE TITLE
Conflicting with any kind of infinite scroll plugin. 

### ISSUE THREAD

**Issue by suraiya-yasmin** [ConnectThink/WP-SCSS#234]
This plugin is conflicting with any kind of infinite scroll plugin. The issue is: infinite scroll is working fine for logged in user, but it's not working for logged out user. 

NB: No cache plugin installed.

**Comment by suraiya-yasmin** [comment]
Here is the link https://tannybunny.com/shop/

**Comment by shadoath** [comment]
@suraiya-yasmin did you get this resolved?
