### ISSUE TITLE
Wrong path in header generated

### ISSUE THREAD

**Issue by D-ultimate** [ConnectThink/WP-SCSS#235]
When using base location as Wp-scss plugin, the path in header is generated as
" wp-content/**plugins/custom-css/ordered_list.css**?ver=1661411438' "
instead of
" wp-content/**plugins/wp-scss/custom-css/ordered_list.css**?ver=1661411438' "

**Comment by shadoath** [comment]
What version of the plugin do you have?

**Comment by shadoath** [comment]
Not enough info provided
