### ISSUE TITLE
Warning: Array to string conversion

### ISSUE THREAD

**Issue by megseoh** [ConnectThink/WP-SCSS#236]
I’m working on a new site with WP_DEBUG enabled & I’m seeing this warning:

`Warning: Array to string conversion in /www/website_447/plugins/wp-scss/scssphp/src/Compiler.php on line 878`

It's causing issues with pages loading & sometimes causes the page to stall out completely.

**Comment by shadoath** [comment]
Give version 3.0.0 a test and see if you still have this issue. the SCSSPHP compiler has been upgraded.

**Comment by shadoath** [comment]
@megseoh can you see if version 4.0.2 will work for you?

**Comment by shadoath** [comment]
@megseoh, unless you can provide more info or test on v4 I'm going to close this issue
