### ISSUE TITLE
Autoprefixer

### ISSUE THREAD

**Issue by darkvovich** [ConnectThink/WP-SCSS#26]
How about to add autoprefixer functionality? I think it will be very useful.
https://github.com/vladkens/autoprefixer-php

**Comment by brrn** [comment]
Not a bad idea, we will look into this!

**Comment by nathansmonk** [comment]
+1

**Comment by jennschlick** [comment]
+1! I rely heavily on Autoprefixer, especially for Flexbox syntax.

**Comment by atav32** [comment]
so was this added or just closed?

**Comment by vpillinger** [comment]
It looks like it was just closed.

**Comment by NeOMakinG** [comment]
I've still added Autoprefixer to wp-scss myself, but you need Node installed because that's just a PHP wrapper sending a cmd !

If someone still find a native php autoprefixer, I can add it too and push it to this repo !

**Comment by garrettw** [comment]
@brrn what was the verdict of "looking into this"?
