### ISSUE TITLE
Permissions problem: 

### ISSUE THREAD

**Issue by catinfire** [ConnectThink/WP-SCSS#27]
Hi
I am receiving this message, I copied the permissions model from other installation but in this particular site I can't solve it:

/wp-plugins/wp-scss/cache/ 
"File Permission Error, permission denied. Please make the cache directory writable."

Thanks in advance for your help.

**Comment by brrn** [comment]
Hi Catinfire, if you have already ensured that your cache folder is writable, you can also check ownership. You may run into issues if the folder is not owned by the web user.

**Comment by catinfire** [comment]
Thanks!

Saludos,

Carlos Talaga Muñoz.
Freelance interactive web designer and SEO
Barcelona, Spain

www.carlostalaga.com - www.webmedia.co
cat@carlostalaga.com
skype: carlostalaga
tel: (34) 645 16 7256

**Comment by ryansigg** [comment]
I'm experiencing this same issue; to make it work I need to change the permissions to 777 (I'm having the same issue with the CSS directory, needing to set to 777).
It works for now, but I guess I will just have to change the permissions back when the site goes live.

**Comment by shawnrosspeters** [comment]
Is there a way to change the directory wp-scss writes to? I'm using Pantheon and it's recommended to keep cache files in the files directory. For example, /wp-content/uploads/wp-scss or /wp-content/uploads/cache.

Is this possible? Also, if I should create an new thread from this please let me know.

**Comment by mccreeker** [comment]
I'm using Windows and got my install from a copied wordpress folder from another developer's Mac (believe me, this was the easiest way for me to take over the project), and getting the error even though the cache folder doesn't exist.

Is there some button or link I'm supposed to click in the plugin to create this folder properly? Or should I just manually create it? I haven't used the plugin at all, I'm not sure I'll need to, the previous developer just installed it for whatever styling thing they may or may not have actually done.

**Comment by garrettw** [comment]
> Is there some button or link I'm supposed to click in the plugin to create this folder properly? Or should I just manually create it?

I've never had to manually create any cache or click any button to do it.

**Comment by mccreeker** [comment]
Thanks for the info @garrettw, does anyone know what I'm supposed to do?

**Comment by mccreeker** [comment]
I created the cache folder, the error went away, I don't know if that's what I'm supposed to do, but this seems like a bug. If the folder doesn't exist, the program should create it, it's a cache folder, it shouldn't show a fake permissions error on a folder that doesn't exist, unless it's unable to create the folder, in which case the error is incorrect.

My server is able to create files and folders, so I don't understand why there's an issue with this folder.

**Comment by mmoollllee** [comment]
Still struggeling with this. As I use the plugin with a local / stage / prod deployment workflow, I have to recreate the folder for every deploy. Would be nice if this get's fixed :)

**Comment by polyakoff** [comment]
@mmoollllee 
This helped, thank you!

**Comment by jackiebain** [comment]
Hi,

I am having the same issue, keep getting this error...

"File Permission Error, permission denied. Please make the cache directory writable."

When I try to make a cache directory I get 'permission denied'

When I try to change the directory file permissions on the wp-scss directory to 'write' it looks like it has worked but I still get the 'permission denied' error when I try to create the cache directory.

Is there somewhere else I need to change these permissions?

Thanks!

Jackie

**Comment by mmoollllee** [comment]
> When I try to change the directory file permissions on the wp-scss directory to 'write' it looks like it has worked but I still get the 'permission denied' error when I try to create the cache directory.
This is unrelated to WP-SCSS. Try to create the folder with sudo. You have to find out how to create the folder in your hosting-environment.

> Is there somewhere else I need to change these permissions?
No.
