### ISSUE TITLE
lighten() function doesn't work with variables

### ISSUE THREAD

**Issue by fksr86** [ConnectThink/WP-SCSS#3]
i'm trying to use a lighten() function with a variable, like this:

`background-color: lighten($color:, 10%);`

but it results in a compiling error:

```
  "expecting color: failed at `background-color: lighten($color:, 10%);`
```

i've searched someone who had the same error, and i found this: http://stackoverflow.com/questions/20489656/foundation-5-scss-compilation-via-scssphp
it suggests to updates scssphp to 0.0.9.

i've updated my scssphp version inside the plugin, but the error still shows.

**Comment by sgnl** [comment]
Caveat: not related to issue posed by OP but related and I got here from a search result.

FWIW, if a variable doesn't actually return a type "color" it'll product this error. The OP did not mention what the value of `$color` actually was when the error occurred but here's the information I've gathered:

Make sure that your variable is set to an actual color and the name has the correct name:

```css
$color: rgb(38, 145, 191); // this is okay
$color: RGB(38, 145, 191); // this is NOT okay, notice the uppercased R-G-B, sass will not recognize this as a color
```

I'm able to reproduce the error by misspelling `rgba`, `hsl`, `hsla`, etc.
