### ISSUE TITLE
Newer Bourbon support

### ISSUE THREAD

**Issue by mattejames** [ConnectThink/WP-SCSS#33]
Hello,

I just download the plug-in and am very excited to start working with it.  One hitch I ran into was the support for Bourbon appears to be somewhat old.  I downloaded the latest version of Bourbon, but ran into some SASS compiling errors.  I was able to fix them so far by using Bourbon v3.2.4, but the Bourbon team is now on v4.2.0 stable and actively working on v5.0.

I imagine that your support is limited by the PHP-based SASS compiler used behind the scenes, but didn't know if there was an update there.

Thanks!

**Comment by alexelash** [comment]
Hi,

I'm also wondering about support for the latest version of Bourbon. Is that something that is actively being worked on? Thank you!

**Comment by killexx** [comment]
Hello,
Does anyone made Bourbon to work with WP-SCSS?

**Comment by brrn** [comment]
We have updated scsphp to the latest version, 0.6.6.
