### ISSUE TITLE
Fatal Error Upon Saving

### ISSUE THREAD

**Issue by indadam** [ConnectThink/WP-SCSS#34]
I installed the plugin and upon adding the directories I get this error (I've replaced my URL with [BASE_URL]:

    Fatal error: Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct([BASE_URL]/wp-content/themes/15SPRK001-sparksite-wp/scss/foundation.scss): failed to open dir: Not a directory' in [BASE_URL]/wp-content/plugins/wp-scss/class/class-wp-scss.php:139 Stack trace: #0 [BASE_URL]/wp-content/plugins/wp-scss/class/class-wp-scss.php(139): RecursiveDirectoryIterator->__construct('/home/indclient...') #1 [BASE_URL]/wp-content/plugins/wp-scss/wp-scss.php(153): Wp_Scss->needs_compiling() #2 [BASE_URL]/wp-settings.php(215): include_once('/home/indclient...') #3 [BASE_URL]/wp-config.php(96): require_once('/home/indclient...') #4 [BASE_URL]/wp-load.php(29): require_once('/home/indclient...') #5 [BASE_URL]/wp-admin/admin.php(31): require_once('/home/indclient...') #6 /home/indclient/sample in [BASE_URL]/wp-content/plugins/wp-scss/class/class-wp-scss.php on line 139

The SCSS is just ZURB's Foundation framework and complies fine on my machine. I'm just not understanding the error, thanks!

**Comment by brrn** [comment]
Are you still having trouble?

**Comment by indadam** [comment]
I think I ended up moving on and doing something else. Thanks for checking though.

**Comment by maxwellcarl** [comment]
think i got this same error
