### ISSUE TITLE
Comments problem

### ISSUE THREAD

**Issue by vskochko** [ConnectThink/WP-SCSS#36]
In Compressed & nested mode do not delete comments like this:
/*==============================
= comment =
==============================*/
only  comments in one line
// comment
Possible to fix it?

**Comment by mndewitt** [comment]
I added a minify option in a PR (https://github.com/ConnectThink/WP-SCSS/pull/30), which cuts out all comments and new lines.  Might be what you are looking for, comment in approval and hopefully they will merge it...

**Comment by brrn** [comment]
This has been merged.
