### ISSUE TITLE
Please update included version of phpscss

### ISSUE THREAD

**Issue by mjess** [ConnectThink/WP-SCSS#39]
Hi,
I had some trouble compiling some advanced scss code. After manually updating the phpscss version included in this plugin to the latest available (0.1.7) it works perfectly.
Please update the phpscss version which ships with this great plugin, such that it is not required any more to update it manually. 
Latest version available here: https://github.com/leafo/scssphp/releases/tag/v0.1.7

In case someone wants to verify the problem with the currently included version: Try to compile the font face mixin defined in this article: http://clubmate.fi/scss-font-face-mixin/

**Comment by brrn** [comment]
If you have some time to do a pull request, I'll be happy to merge it.

**Comment by nathansmonk** [comment]
I've just tried to compile a Sass Map, which failed, presumably due to this issue.

**Comment by webakimbo** [comment]
+1

Importing a stylesheet for a 3rd party js library and it's choking on the sass map definition in [this line](https://github.com/noraesae/perfect-scrollbar/blob/master/src/css/themes.scss#L1).

**Comment by pawelkmpt** [comment]
@brrn I see that there's pull request for this issue (#52). Any estimation when merge can be done?

Version 0.0.12 of scssphp included in this plugin was released on July 6, 2014...

**Comment by MarcGuay** [comment]
+1

**Comment by fredconv** [comment]
does anybody have an idea to manually update scssphp ? 

i ve tried to just replace the scss.inc.php by the new one with all needed subfolder but i got a white crash :) 

<pre>
Fatal error: Uncaught Error: Class 'scssc' not found in /my_site/www/wp-content/plugins/wp-scss/class/class-wp-scss.php:30 Stack trace: #0 /my_site/www/wp-content/plugins/wp-scss/wp-scss.php(149): Wp_Scss->__construct('/my_site/...', '/my_site/...', 'scss_formatter_...') #1 /my_site/www/wp-settings.php(255): include_once('/my_site/...') #2 /my_site/www/wp-config.php(124): require_once('/my_site/...') #3 /my_site/www/wp-load.php(37): require_once('/my_site/...') #4 /my_site/www/wp-blog-header.php(13): require_once('/my_site/...') #5 /my_site/www/index.php(17): require('/my_site/...') #6 {main} thrown in /my_site/www/wp-content/plugins/wp-scss/class/class-wp-scss.php on line 30
</pre>

**Comment by brrn** [comment]
Sorry for the delay folks, scssphp has been updated to 0.6.6.
