### ISSUE TITLE
Unable to Generate SCSS to Theme Root

### ISSUE THREAD

**Issue by stvnrynlds** [ConnectThink/WP-SCSS#40]
I've tried this plugin on two websites now so far, and it's worked wonderfully, except for one thing: if I set the CSS location to `/` — that is, the theme folder — then it won't work (my SCSS location is set to `/scss/`). As soon as I change the CSS location to a subdirectory like `/css/` it starts generating there. This means I have to have two stylesheets, one `style.css` in the theme folder to set the WP theme data, and another in `/css/master.css` to hold the SCSS-generated files.

As I said, I've tried this on two different servers and the same issue presents. Am I doing something wrong?

**Comment by brrn** [comment]
Hello, I've tested compiling to the theme root folder and it does work for me. We have made quite a few updates so give this another shot.
