### ISSUE TITLE
Permissions Error on Pantheon

### ISSUE THREAD

**Issue by r4in** [ConnectThink/WP-SCSS#41]
So I'm currently this plugin on Pantheon(it's a nice platform for WP sites) and I get a compile error. 

/wp-plugins/wp-scss/cache/ 
"File Permission Error, permission denied. Please make the cache directory writable."

Is the cache directory generated by the plugin? Or does it generate it somewhere else? 
I tried changing the permission settings of the folder above to writable and it's not working.

**Comment by mndewitt** [comment]
If you have shell access to your server, try changing the file permissions to 755 on that directory.  If that does not work, try changing the folder owner to www-data:root (or whatever user Apache has the rights to).

It is almost certainly a file permissions issue.  If you don't have shell access, reach out to Pantheon for help.
