### ISSUE TITLE
Release tagging

### ISSUE THREAD

**Issue by MarcGuay** [ConnectThink/WP-SCSS#42]
Hi,

Would it be possible to tag the releases either in Github or Wordpress' SVN repo?  I would like to pull v1.1.8 using composer rather than "dev-master" and getting potential breaky updates.

Thanks for your work, this is helping me with a new project, specifically the ability to define SASS variables with Wordpress.

Marc

**Comment by brrn** [comment]
New version has been tagged and released on WP SVN

**Comment by MarcGuay** [comment]
Beautiful, thank you
