### ISSUE TITLE
WP-SCSS does nothing. No compile. No output. No error. No log. 

### ISSUE THREAD

**Issue by dmxt** [ConnectThink/WP-SCSS#45]
I'm using child theme, with directory structure:

```
child theme directory
└───assets
    ├───css
    └───scss
    │   main.scss
```

WP-SCSS settings:
![Settings](http://i.imgur.com/zblSq5R.png)

After making changes to main.scss, it doesn't compile or update main.css

What is the problem here?

**Comment by crazypinger** [comment]
I'm finding the same behavior

**Comment by crazypinger** [comment]
Sorry I figured out that I needed to add define('WP_SCSS_ALWAYS_RECOMPILE', true); in my functions file for it to work.

Thanks for the plug-in

**Comment by timbotcom** [comment]
I believe that causes the scss to recompile every time the page is loaded. Not a viable solution other than in dev. 

From what I understand from the documentation, its supposed to know to recompile every time there's a change to any of the scss files in the sass folder...

**Comment by gavin310** [comment]
My theme doesn't use WordPress's standard head functions, so I had to edit the plugin. In wp-scss.php in the plugin's root folder, I changed:

add_action('wp_head', 'wp_scss_needs_compiling');

to

add_action( 'wp_loaded', 'wp_scss_needs_compiling' );

**Comment by shanecarmody** [comment]
@gavin310 solution worked for me, is this change going to be made in the plugin?

**Comment by brrn** [comment]
We can look into this. Would wp_loaded be a better hook for the plugin to use by default?

**Comment by garrettw** [comment]
Based on what I see [here](http://rachievee.com/the-wordpress-hooks-firing-sequence/), I wonder if `setup_theme` might actually be the ideal hook to use.

**Comment by brrn** [comment]
@garrettw that looks promising. It would ensure that the function fires every time, while also keeping it before theme load. We'll test this.

**Comment by smontoro** [comment]
> Sorry I figured out that I needed to add define('WP_SCSS_ALWAYS_RECOMPILE', true); in my functions file for it to work.
> 
> Thanks for the plug-in

That worked for me too! Thanks!

**Comment by mdarmanin** [comment]
Guys, since recent update, my SCSS wasn't compiling anymore so after loads of time wasting trying to find out why, I found out that define('WP_SCSS_ALWAYS_RECOMPILE', true); was required for me too. Try to prevent this in future releases or at least add a setting in plugin to turn this on without searching half the net. Rigid testing may also help.
