### ISSUE TITLE
Trouble with imports & mixins

### ISSUE THREAD

**Issue by snigel1** [ConnectThink/WP-SCSS#47]
Great idea but it feels a bit unstable and gives compile errors on stuff that would compile offline, seems sporadical aswell.

For example, if i put a mixin in one file and try to use it in another (both files are @import:ed) it seems to not find the mixin. If i move it to the same file as where i try to use, it works.

Any ideas?

**Comment by brrn** [comment]
Are you using at least PHP version 5.4? If so, try this again. We just pushed a bunch of updates including an update to scssphp version 0.6.6
