### ISSUE TITLE
@at-root instruction is not interpreted

### ISSUE THREAD

**Issue by charli-polo** [ConnectThink/WP-SCSS#51]
I discovered this small issue while trying to compile bootstrap, the glyphicon are broken because of that.
I suppose this is an issue with scssphp, so maybe this isn't the right place to report the bug... Still it can help someone trying to lokk into the issue.

Great plugin btw, thx a lot !

**Comment by imjosecampos** [comment]
+1 having the same issue.

**Comment by brrn** [comment]
Thanks! We have updated to the latest version of scssphp.
