### ISSUE TITLE
Why is scssphp version so far behind?

### ISSUE THREAD

**Issue by efc** [ConnectThink/WP-SCSS#53]
Just curious why the compiler is such an old version? Looks like the [v0.0.12](https://github.com/leafo/scssphp/releases/tag/v0.0.12) being used here was released in July 2014 and [leafo/scssphp](https://github.com/leafo/scssphp) is up to [v0.6.3](https://github.com/leafo/scssphp/releases/tag/v0.6.3) as of this January. That's over 25 release behind. 

Did something creep in along the way that does not play well with WordPress or this plugin?

**Comment by efc** [comment]
There seems to be a pull request (#52) to bring this up to 0.6.3. Can this be merged?

**Comment by MarcGuay** [comment]
I'm running into some issues that seem to be caused by an old compiler - would like to see this as well.

**Comment by mamela** [comment]
Having issues compiling, is this still actively being developed?

**Comment by fredconv** [comment]
does anybody have an idea to manually update scssphp ? 

i ve tried to just replace the scss.inc.php by the new one with all needed subfolder but i got a white crash :) 

<pre>
Fatal error: Uncaught Error: Class 'scssc' not found in /my_site/www/wp-content/plugins/wp-scss/class/class-wp-scss.php:30 Stack trace: #0 /my_site/www/wp-content/plugins/wp-scss/wp-scss.php(149): Wp_Scss->__construct('/my_site/...', '/my_site/...', 'scss_formatter_...') #1 /my_site/www/wp-settings.php(255): include_once('/my_site/...') #2 /my_site/www/wp-config.php(124): require_once('/my_site/...') #3 /my_site/www/wp-load.php(37): require_once('/my_site/...') #4 /my_site/www/wp-blog-header.php(13): require_once('/my_site/...') #5 /my_site/www/index.php(17): require('/my_site/...') #6 {main} thrown in /my_site/www/wp-content/plugins/wp-scss/class/class-wp-scss.php on line 30
</pre>

**Comment by efc** [comment]
I ended up using a fork at https://github.com/rchq/WP-SCSS which was updated to use scssphp 0.6.3.

**Comment by fredconv** [comment]
Thanks 
indeed , it works
That was crashing a scss map variable declaration :) 

Now everything is ok !
