### ISSUE TITLE
Passing variables with files extensions

### ISSUE THREAD

**Issue by GavinJaynes** [ConnectThink/WP-SCSS#55]
Hi, I'm trying to pass some fields set in the WP options page to the SCSS using the wp_scss_variables filter. 

The issue is they are image paths ( for background image changing ) and the compiler seems to strip out characters such as .png, .jpg, // and so on. 

Can I turn off this "sensitization"? 

Thanks. Otherwise it's a good plugin if you are not using Gulp or Grunt.

**Comment by sinsimon** [comment]
Yes, I have the same issue. Any workaround found?

**Comment by shadoath** [comment]
the `wp_scss_variables` uses ScssPhp's Parser and thus would not fall into the case of this plugin. 
WP-SCSS has been recently updated to 1.5.2 which may have changed functionality.
