### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by maxwellcarl** [ConnectThink/WP-SCSS#58]
keep getting this error message on all the live sites i try to use this on :/ this is a super useful plugin when it does work. 

<img width="1174" alt="screen shot 2016-07-24 at 6 31 54 pm" src="https://cloud.githubusercontent.com/assets/880239/17088183/f454ad12-51cc-11e6-950f-9148e445377f.png">

**Comment by brrn** [comment]
Are you using at least PHP version 5.4? If so, try this again and report back. We just pushed a bunch of updates.
