### ISSUE TITLE
Please update Wordpress plugin to the latest

### ISSUE THREAD

**Issue by wispstudios** [ConnectThink/WP-SCSS#59]
Can we get the plugin updated to the latest? I can manually overwrite the plugin files with what's here on github and it works great, but it is a pain to have to manually update on every single site.

**Comment by erikeliasson** [comment]
This is of super-highg priority for me as well! Please update...

**Comment by brrn** [comment]
We have updates to this plugin in our queue but not very high on the list. If you have overwritten the plugin files and it works, why not submit a pull request?
