### ISSUE TITLE
Use it in theme?

### ISSUE THREAD

**Issue by dmbostan** [ConnectThink/WP-SCSS#60]
Hi!

I was wondering if there is a possibility to use WP-SCSS from theme and not as a standalone plugin?

**Comment by wpexplorer** [comment]
You could dump the plugin into the theme, but there isn't any point or benefit in doing so. Your finished theme should already be compiled for the end user ;)

**Comment by garrett-eclipse** [comment]
Hi @dmbostan 

I recently built a theme using ACF for theme options which upon save re-renders scss via leafo's scssphp found here;
https://github.com/leafo/scssphp
*This is the same library that the WP-SCSS plugin utilizes.

I just set-up a gist so you can see;
https://gist.github.com/garrett-eclipse/cb1f74cf5368c09ce5bc25f83fb9b667

I place the file in my theme and just include via functions.php.

Note the filters are all using acf/save_post from Advanced Custom Fields plugin.

Hope that helps,
Cheers

**Comment by dmbostan** [comment]
@garrett-eclipse thank you!
