### ISSUE TITLE
Just updated the plugin and got an error once I saved my .scss files

### ISSUE THREAD

**Issue by mbgulden** [ConnectThink/WP-SCSS#67]
This error happened after I updated the plugin and saved an .scss file:
**Fatal error: Class 'scss_formatter' not found in activeoahu.dev\wp-content\plugins\wp-scss\scssphp\src\Compiler.php on line 189**

Most of my pages don't load anymore due to this error that looks to originate with the WP-SCSS plugin. I haven't been able to find anything online about this issue, but if you can point me in the right direction I can hopefully figure it out.

Any help would be appreciated.

Thanks!
-Mike

**Comment by brrn** [comment]
What version PHP and WordPress are you running?

**Comment by mbgulden** [comment]
PHP 5.6.8 
WP 4.7

**Comment by mbgulden** [comment]
Ended up just pulling the most recent version of the plugin from here and it worked just fine. for some reason it wasn't working when I downloaded it from the plugin marketplace of WordPress. Thanks!

**Comment by brrn** [comment]
Andy seems to have discovered the root of the issue https://github.com/ConnectThink/WP-SCSS/issues/68
