### ISSUE TITLE
Update WP-SCSS to 1.2.2 leads to error "Class 'scss_formatter' not found ..."

### ISSUE THREAD

**Issue by andy-tschiersch** [ConnectThink/WP-SCSS#68]
You can solve this error by simply updating the WP-SCSS settings in admin panel.

This error occurs after plugin update and after changing scss.

The reason is there are new Compiling Modes, and the old Compiling Modes are invalid now for the new version. The update process should ensure that the settings for the Compiling Mode also set to an valid mode.

In my case I've updated from 1.9 to 1.2.2

**Comment by johnpeak** [comment]
Sorry, but I still get this error with the 1.2.2 release.  It's not clear how I can roll this back so have deactivated for now and things seem to work.  Any ideas on how to troubleshoot?

**Comment by brrn** [comment]
Did you re-save your settings in the WP-SCSS admin panel as Andy suggests?

**Comment by johnpeak** [comment]
You're right.  That fixed it.  thx!!

**Comment by brrn** [comment]
No problem!
