### ISSUE TITLE
Foundation 6 Compilation Error

### ISSUE THREAD

**Issue by maplesyrupsucker** [ConnectThink/WP-SCSS#70]
Has anyone else experienced issues compiling Foundation 6 using wp-scss. Getting compiling errors that seem to change from time to time. It looks like issues with variables in flex grid and gris scss files.

It looks like scssphp has had this issue reported but no sign of life over there.

[https://github.com/leafo/scssphp/issues/446](https://github.com/leafo/scssphp/issues/446)

Anyone come up with a fix?

**Comment by shadoath** [comment]
Based on the link and comments post this issue being submitted this looks to now be fixed.
