### ISSUE TITLE
Plugin overwrites child theme template header

### ISSUE THREAD

**Issue by DonKoko** [ConnectThink/WP-SCSS#75]
As we all know, when using a child theme we have to use a template header in the style.css([https://codex.wordpress.org/Child_Themes](https://codex.wordpress.org/Child_Themes)). 
I believe that when compiling, the plugin is not having that in mind and overwriting the child header.

Would be great if this can be kept in mind to not create the issue of users' child themes breaking.

**Comment by brrn** [comment]
You can create a style.css in your theme root that only includes your child theme template header. Then compile your scss to another location, like /lib/css.

If you set it up this way, you don't have to worry about the plugin overwriting anything.

**Comment by garrettw** [comment]
I cannot duplicate this issue. In fact, I've been using this plugin successfully with SCSS files in `/scss/` and compiling to `/`. My child theme header has always been left intact.
