### ISSUE TITLE
Plugin not compiling with understrap theme

### ISSUE THREAD

**Issue by jamalvr** [ConnectThink/WP-SCSS#76]
Hello there. I wanted to use a basic bootstrap/SASS theme and stumbled upon understrap. It had SCSS files ready to edit, but for a reason it says that I have multiple undefined properties. 

We fixed it with placing the SRC files from the parent theme into the child theme directory. But after that it was still unable to push the changes that I added.

**Comment by garrettw** [comment]
Hi @jamalvr are you still having this issue? If so, can you provide some code and/or directory structure so I can try to figure it out?
