### ISSUE TITLE
Plugin is unable to include SCSS files in subfolder

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [ConnectThink/WP-SCSS#78]
In my installation, the SCSS file structure is assets/scss/ path I have provided to plugin, that includes scss files itself and also contains a folder config inside it ( assets/scss/config/ ), this also includes SCSS files but plugin is unable to include it and showing errors, how it should be fixed ?

**Comment by garrettw** [comment]
1. What are the errors?
2. What are the filenames inside assets/scss/config/ that you're trying to use?
3. How are you trying to include those files?

**Comment by garrettw** [comment]
If you don't wish to follow up on this issue, feel free to close it.
