### ISSUE TITLE
import without underscores

### ISSUE THREAD

**Issue by emanueljacob** [ConnectThink/WP-SCSS#80]
I would like to create sass compiling in combination with wordpress customizers live preview.
So the goal is to enqueue all scss compilated files one by one for the wordpress customizer only and recompile everytime the user is making changes in customizer (selecting color, font size etc). 
if a specific scss file changes (because of a change in customizer) ONLY this scss file is going to be compiled. This should speed up the compiling process in live view.

I achieve this, by enqueueing all compiled css files one by one in customizers view only. 
Only if the user is clicking the save button in wordpress customizer I hook up into the customizer_save_after action and call a custom function in order to merge all css files into one style.css file which I then enqueue for front page purposes (dequeued in customizer view) once. This works fine.

My problems:
- I read, if I would use the @import declaration without underscores, the imported files were not compiled into the main css file. instead those files were compiled into separated files.
But actually this does not happen. I did not change anything, but all files with and without underscores are being merged into the main css... what can i do to compile all files which I imported by using the @import statement, into separated files?

- As explained before, I want to compile each file (and all file dependencies) only on change. Is this even possible? Or does wp-scss compile every scss file again, when there was a change in one file.

**Comment by garrettw** [comment]
Your first issue may not relate to this plugin at all, but rather to Sass in general.
A bit about `@import`:
- `@import "partial";` first looks for a file named `_partial.scss`, and then if I understand correctly, if that doesn't exist, it will then look for `partial.scss`.
- `@import "partial.scss";` will only look for `partial.scss`.
- `@import "partial.css";` will NOT "merge" the files but will pass the import statement through to the final generated CSS -- meaning that the end user's browser will have to request that CSS file from the server.
- You cannot use `@import` to make a SCSS file compile without being merged in.

[Read more here.](http://vanseodesign.com/css/sass-the-import-directive/)
Also, WP-SCSS will automatically compile any SCSS file in the specified directory that does not begin with an underscore. However, in my experience, automatically enqueueing them may not work, so you might have to do that part manually.

To address your second question, WP-SCSS only re-compiles files when they've changed.

**Comment by brrn** [comment]
Thank you for your concise response @garrettw.

@ecksite did you find a way to make this work in the customizer for you? This is an intriguing idea and I wouldn't mind looking into more ways to make this easier for people.
