### ISSUE TITLE
@include not working

### ISSUE THREAD

**Issue by w-biggs** [ConnectThink/WP-SCSS#81]
Hi. I'm unable to get WP-SCSS to work with @include statements.

I have a few mixins in a subfolder called /vendors/. Inside there, there's a scss file that imports a few files from another subdirectory.

In the root scss directory, I have the correct files imported in my main.scss. In my local, gulp-sass environment, I'm able to use the `@include` statements these mixins provide. However, this seems to be doing nothing with WP-SCSS - it's not even throwing any errors.

I don't know what I could be doing wrong on my end - the exact same code was working with gulp-sass. Any ideas? Thank you so much!

Here's the directory structure for the sass files:
![image](https://user-images.githubusercontent.com/3406010/30986569-e04507ca-a461-11e7-889e-34519f15e0b8.png)
![image](https://user-images.githubusercontent.com/3406010/30986629-19cd40ac-a462-11e7-833b-671dac17b8dc.png)
![image](https://user-images.githubusercontent.com/3406010/30986649-233b343c-a462-11e7-9a29-51f201dde6ba.png)

**Comment by brrn** [comment]
Hi @w-biggs, sorry for the late response. Did you find a solution to this?

**Comment by shadoath** [comment]
ScssPhp updated to 1.5.2. If you can test on that and still have an error ping this thread. Otherwise, I'm closing as being out of date.
