### ISSUE TITLE
unable to find directories

### ISSUE THREAD

**Issue by zachisit** [ConnectThink/WP-SCSS#83]
my codebase is as such:

theme/main.scss
theme/main.css

i put this into the plugin settings and i get attached screenshot.
![2017-11-30_0730](https://user-images.githubusercontent.com/5091177/33431122-286f158e-d5a1-11e7-8076-72d1f2cab981.png)

attached screenshot shows proof of my assets location that is based off of the root of the theme.

![2017-11-30_0734](https://user-images.githubusercontent.com/5091177/33431119-24ec148e-d5a1-11e7-9468-25ae62747a64.png)

my only guess is this plugin requires me to put these two files in an actual directory of the theme, and not the root of the theme? please let me know what i am missing here.

**Comment by garrettw** [comment]
🤦‍
Since when do filenames end with a slash?
This is really common sense.
Also, look at the configuration screen again and tell me - did it ask you for filenames, or directories?

**Comment by zachisit** [comment]
ah ok perfect. i'm not a fan of putting the sass into a directory, but will do in order to use this plugin and save me the time of compiling locally. moved into a directory, updated the plugin, and it works great. many thanks.

you may want to think of adding a simple jquery check with regex: if the input for these two fields involves anything with a period etc then throw an error and clear the input fields. this would be helpful for utterly stupid jerks like myself.

**Comment by zachisit** [comment]
ah ok good to know about possibly setting it to `/`, but it is probably sloppy of me to just put those assets in root. i've moved my sass into a proper directory, with help of this plugin forcing me to. so that is good.

dang that is very smart about setting the scss to compile into a `/style.css` on root. that would remove my need to create a blank `/style.css` file with the need to write `@import url("sass/main.scss");` in it for all of my themes. i guess the only reason i did this was to include the normal theme comment block WordPress requires at the top of the `style.css` file. i assume your plugin will compile your `/scss/style.scss` into your `/style.css` and keep whatever WordPress theme dependent comment block at top of file - thus removing my blank `/style.css` file?

i personally am not into having the plugin enqueue . i just write it manually into the theme's functions file like a loser.

**Comment by garrettw** [comment]
> i assume your plugin will compile your `/scss/style.scss` into your `/style.css` and keep whatever WordPress theme dependent comment block at top of file - thus removing my blank `/style.css` file?

Yes, but only because I copied that comment block to the top of my SCSS file.

**Comment by zachisit** [comment]
ok this is amazing advice. very much appreciated!
