### ISSUE TITLE
Notice on settings page about screen_icon() being deprecated

### ISSUE THREAD

**Issue by DeveloperWilco** [ConnectThink/WP-SCSS#84]
With WP_DEBUG on true there is a notice on the plugin' setting page wich says that the screen_icon() function is deprecated since WP 3.8.0.
Its not harmful but it would be nice if it got removed/replaced.

it's on line 42 of options.php

[screen_icon()](https://developer.wordpress.org/reference/functions/screen_icon/)

Thanks in advance!

**Comment by brrn** [comment]
screen_icon() has been removed.
