### ISSUE TITLE
It's setup correctly but not working? 

### ISSUE THREAD

**Issue by yomilky** [ConnectThink/WP-SCSS#85]
The main file is /SCSS/style.scss, which should compile to /CSS/style.css, but /CSS/ is still empty.   Tried changing the compiling mode and making several changes to style.scss, plus added some @imports and made changes to them = nothing. Thoughts?

**Comment by garrettw** [comment]
Can you provide a screenshot of your configuration page?

**Comment by yomilky** [comment]
It's working, but even with the functions.php to refresh > compile there's a 10 min delay...guessing it's on the hosting side.
