### ISSUE TITLE
Error with 1.2.3 update

### ISSUE THREAD

**Issue by InnGHDev** [ConnectThink/WP-SCSS#88]
Hello,

The update published this morning is returning the following errors.

``Warning: include_once(SITE PATH/wp-content/plugins/wp-scss/scssphp/src/Exception/RangeException.php): failed to open stream: No such file or directory in SITE PATH/wp-content/plugins/wp-scss/scssphp/scss.inc.php on line 14

Warning: include_once(): Failed opening 'SITE PATH/wp-content/plugins/wp-scss/scssphp/src/Exception/RangeException.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in SITE PATH/wp-content/plugins/wp-scss/scssphp/scss.inc.php on line 14

Warning: include_once(SITE PATH/wp-content/plugins/wp-scss/scssphp/src/SourceMap/Base64VLQEncoder.php): failed to open stream: No such file or directory in SITE PATH/wp-content/plugins/wp-scss/scssphp/scss.inc.php on line 28

Warning: include_once(): Failed opening 'SITE PATH/wp-content/plugins/wp-scss/scssphp/src/SourceMap/Base64VLQEncoder.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in SITE PATH/wp-content/plugins/wp-scss/scssphp/scss.inc.php on line 28

Warning: include_once(SITE PATH/wp-content/plugins/wp-scss/scssphp/src/SourceMap/SourceMapGenerator.php): failed to open stream: No such file or directory in SITE PATH/wp-content/plugins/wp-scss/scssphp/scss.inc.php on line 29

Warning: include_once(): Failed opening 'SITE PATH/wp-content/plugins/wp-scss/scssphp/src/SourceMap/SourceMapGenerator.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in SITE PATH/wp-content/plugins/wp-scss/scssphp/scss.inc.php on line 29``

**Comment by chrismahon** [comment]
Having the same issue
