### ISSUE TITLE
wp_scss_variables filter does not work

### ISSUE THREAD

**Issue by emojized** [ConnectThink/WP-SCSS#92]
I wrote a plugin with code
```
 
function wp_scss_set_variables(){
    $variables = array(
        'black' => '#ccc',
        'color__content-bg' => '#000',
        'color__content' => 'red'
    );
    return $variables;
}
add_filter('wp_scss_variables','wp_scss_set_variables');
define('WP_SCSS_ALWAYS_RECOMPILE', true);
```

in the scss its defined like
```
$black:                      #000;
$color__content:		#333;
$color__content-bg:		#fff; 

```
I can see  in the source that it somehow reaches the plugin but it does not go into the compiled stylesheet and only is compiling it right when I change the scss itself, which I won't do

Thanks in Advance

**Comment by brrn** [comment]
The plugin will only recompile scss when it sees changes to files in your scss directory (set in the settings). What does your settings page look like?

**Comment by NeOMakinG** [comment]
Use wp_scss_compile on save, it will still execute your filter then compile !

**Comment by rubenvincenten** [comment]
Try adding default to the variables in the files (not the php filter) http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_default
