### ISSUE TITLE
WP-SCSS not changing css file on scss change

### ISSUE THREAD

**Issue by mccreeker** [ConnectThink/WP-SCSS#95]
I reload or hard-refresh the page after an scss change but the css file does not change... I'm not sure how to troubleshoot this.

**Comment by garrettw** [comment]
What are your settings for this plugin?

**Comment by mccreeker** [comment]
![image](https://user-images.githubusercontent.com/33667567/36693808-a861a070-1af9-11e8-91f8-d66e68a49fd3.png)

**Comment by garrettw** [comment]
Ok, what does your theme's `style.css` look like?

**Comment by mccreeker** [comment]
I can't upload that; it's a 2000-line code file with proprietary information in it.

It just randomly started working, I don't know why.

What I would like to know is the best way to troubleshoot the issue if it happens again.

**Comment by garrettw** [comment]
Huh. Well at least it's working now. I don't know what to tell you aside from having it configured right. Personally I've had trouble with the "Enqueue Stylesheets" option working, so I just worked around that entirely rather than digging into the plugin and tracking down the issue.

**Comment by mccreeker** [comment]
The settings weren't changed.

What did you do to work around Enqueue Stylesheets not working?

**Comment by garrettw** [comment]
Check out [my comment on issue 83](https://github.com/ConnectThink/WP-SCSS/issues/83#issuecomment-348257428) for the details.
