### ISSUE TITLE
Add CSS to WP Admin

### ISSUE THREAD

**Issue by SnakeO** [ConnectThink/WP-SCSS#96]
Is there any way I can use this to create custom CSS for the *wp-admin* side of things?

**Comment by brrn** [comment]
You should be able to. Create a new scss file for your admin styles and it will be compiled just like other stylesheets.

Do not check "Enqueue Stylesheets" or it will be enqueued on the front end. Instead, add something like this to your theme functions file:

```
function custom_admin_styles() {
	wp_enqueue_style('admin-styles', get_template_directory_uri() . '/css/admin-style.css', array(), filemtime(get_template_directory() . '/css/admin-style.css'), false);
}
add_action('admin_head', 'custom_admin_styles');
```

Not tested, let me know if it works.
