### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by polandrias** [ConnectThink/WP-SCSS#97]
When running a PHP 7 compatibility tester this plugin is listed as a plugin that is not supported by PHP 7. Is this so?

This is the result from the test:

/wp-content/plugins/wp-scss/scssphp/src/SourceMap/Base64VLQEncoder.php
----------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------
 146 | ERROR | Bitwise shifts by negative number will throw an ArithmeticError in PHP 7.0
 146 | ERROR | Bitwise shifts by negative number will throw an ArithmeticError in PHP 7.0
 146 | ERROR | Bitwise shifts by negative number will throw an ArithmeticError in PHP 7.0
----------------------------------------------------------------------------------------------------

**Comment by brrn** [comment]
We are working on an update that includes the new version of scssphp. I'll make sure we run it through the PHP 7 tester before release.
